# Attempt to load a config.make file.
# If none is found, project defaults in config.project.make will be used.
ifndef APPNAME
	APPNAME = ofxGgmlGuiExample
endif

include $(OF_ROOT)/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk
