#pragma once

class ofxVlc4::VideoComponent {
public:
	explicit VideoComponent(ofxVlc4 & owner);

	void applyCurrentPlayerSettings();
	void applyVlcFullscreen();
	void applyVideoInputHandling();
	void applyVideoTitleDisplay();
	void applyVideoAdjustments();
	bool shouldApplyVideoAdjustmentsImmediately() const;
	void applyOrQueueVideoAdjustments();
	void applyPendingVideoAdjustmentsOnPlay();
	void setPendingVideoAdjustApplyOnPlay(bool pending);
	void clearPendingVideoAdjustApplyOnPlay();
	bool hasPendingVideoAdjustApplyOnPlay() const;
	void applyVideoDeinterlace();
	void applyVideoAspectRatio();
	void applyVideoCrop();
	void applyVideoScaleAndFit();
	void applyVideoProjectionMode();
	void applyVideoStereoMode();
	void applyVideoViewpoint(bool absolute = true);
	void clearVideoHdrMetadata();
	void releaseD3D11Resources();
	void updateNativeVideoWindowVisibility();
	bool usesTextureVideoOutput() const;
	bool applyVideoOutputBackend();
	void prepareStartupVideoResources();
	void applyTeletextSettings();
	void applyVideoMarquee();
	void applyVideoLogo();
	VideoAdjustmentEngine resolveActiveVideoAdjustmentEngine() const;
	bool usesShaderVideoAdjustments() const;
	void ensureVideoAdjustShaderLoaded();
	void ensureVideoRenderTargetCapacity(unsigned requiredWidth, unsigned requiredHeight);
	void ensureExposedTextureFboCapacity(unsigned requiredWidth, unsigned requiredHeight);
	void refreshExposedTextureLocked(const VideoStateInfo & state);
	bool applyPendingVideoResize();
	void bindVlcRenderTarget();
	void unbindVlcRenderTarget();
	void videoSwap();
	void clearPublishedFrameFence();
	bool videoResize(const libvlc_video_render_cfg_t * cfg, libvlc_video_output_cfg_t * render_cfg);
	bool videoOutputSetup(const libvlc_video_setup_device_cfg_t * cfg, libvlc_video_setup_device_info_t * out);
	void videoOutputCleanup();
	void videoFrameMetadata(libvlc_video_metadata_type_t type, const void * metadata);
	bool makeCurrent(bool current);
	void * getProcAddress(const char * name) const;
	bool drawCurrentFrame(const VideoStateInfo & state, float x, float y, float width, float height);
	void refreshExposedTexture();
	void draw(float x, float y, float width, float height);
	void draw(float x, float y);
	VideoHdrMetadataInfo getVideoHdrMetadata() const;
	float getVideoScale() const;
	void setVideoScale(float scale);
	VideoProjectionMode getVideoProjectionMode() const;
	void setVideoProjectionMode(VideoProjectionMode mode);
	VideoStereoMode getVideoStereoMode() const;
	void setVideoStereoMode(VideoStereoMode mode);
	float getVideoYaw() const;
	float getVideoPitch() const;
	float getVideoRoll() const;
	float getVideoFov() const;
	void setVideoViewpoint(float yaw, float pitch, float roll, float fov, bool absolute = true);
	void resetVideoViewpoint();
	bool isMarqueeEnabled() const;
	void setMarqueeEnabled(bool enabled);
	std::string getMarqueeText() const;
	void setMarqueeText(const std::string & text);
	OverlayPosition getMarqueePosition() const;
	void setMarqueePosition(OverlayPosition position);
	int getMarqueeOpacity() const;
	void setMarqueeOpacity(int opacity);
	int getMarqueeSize() const;
	void setMarqueeSize(int size);
	int getMarqueeColor() const;
	void setMarqueeColor(int color);
	int getMarqueeRefresh() const;
	void setMarqueeRefresh(int refreshMs);
	int getMarqueeTimeout() const;
	void setMarqueeTimeout(int timeoutMs);
	int getMarqueeX() const;
	void setMarqueeX(int x);
	int getMarqueeY() const;
	void setMarqueeY(int y);
	bool isLogoEnabled() const;
	void setLogoEnabled(bool enabled);
	std::string getLogoPath() const;
	void setLogoPath(const std::string & path);
	OverlayPosition getLogoPosition() const;
	void setLogoPosition(OverlayPosition position);
	int getLogoOpacity() const;
	void setLogoOpacity(int opacity);
	int getLogoX() const;
	void setLogoX(int x);
	int getLogoY() const;
	void setLogoY(int y);
	int getLogoDelay() const;
	void setLogoDelay(int delayMs);
	int getLogoRepeat() const;
	void setLogoRepeat(int repeat);
	int getTeletextPage() const;
	void setTeletextPage(int page);
	bool isTeletextTransparencyEnabled() const;
	void setTeletextTransparencyEnabled(bool enabled);
	void sendTeletextKey(TeletextKey key);
	bool isKeyInputEnabled() const;
	void setKeyInputEnabled(bool enabled);
	bool isMouseInputEnabled() const;
	void setMouseInputEnabled(bool enabled);
	bool isVlcFullscreenEnabled() const;
	void setVlcFullscreenEnabled(bool enabled);
	void toggleVlcFullscreen();
	bool isVideoTitleDisplayEnabled() const;
	void setVideoTitleDisplayEnabled(bool enabled);
	OverlayPosition getVideoTitleDisplayPosition() const;
	void setVideoTitleDisplayPosition(OverlayPosition position);
	unsigned getVideoTitleDisplayTimeoutMs() const;
	void setVideoTitleDisplayTimeoutMs(unsigned timeoutMs);
	bool getCursorPosition(int & x, int & y) const;
	bool isVideoAdjustmentsEnabled() const;
	void setVideoAdjustmentsEnabled(bool enabled);
	VideoAdjustmentEngine getVideoAdjustmentEngine() const;
	VideoAdjustmentEngine getActiveVideoAdjustmentEngine() const;
	void setVideoAdjustmentEngine(VideoAdjustmentEngine engine);
	float getVideoContrast() const;
	void setVideoContrast(float contrast);
	float getVideoBrightness() const;
	void setVideoBrightness(float brightness);
	float getVideoHue() const;
	void setVideoHue(float hue);
	float getVideoSaturation() const;
	void setVideoSaturation(float saturation);
	float getVideoGamma() const;
	void setVideoGamma(float gamma);
	VideoDeinterlaceMode getVideoDeinterlaceMode() const;
	void setVideoDeinterlaceMode(VideoDeinterlaceMode mode);
	VideoAspectRatioMode getVideoAspectRatioMode() const;
	void setVideoAspectRatioMode(VideoAspectRatioMode mode);
	VideoCropMode getVideoCropMode() const;
	void setVideoCropMode(VideoCropMode mode);
	VideoDisplayFitMode getVideoDisplayFitMode() const;
	void setVideoDisplayFitMode(VideoDisplayFitMode mode);
	VideoOutputBackend getVideoOutputBackend() const;
	VideoOutputBackend getActiveVideoOutputBackend() const;
	void setVideoOutputBackend(VideoOutputBackend backend);
	void resetVideoAdjustments();
	std::vector<VideoFilterInfo> getVideoFilters() const;
	std::string getVideoFilterChain() const;
	void setVideoFilterChain(const std::string & filterChain);
	unsigned getVideoOutputCount() const;
	bool hasVideoOutput() const;
	bool isScrambled() const;
	bool queryVideoTrackGeometry(unsigned & width, unsigned & height, unsigned & sarNum, unsigned & sarDen) const;
	void refreshPixelAspectRatio();
	void refreshDisplayAspectRatio();
	ofTexture & getTexture();
	ofTexture & getRenderTexture();
	VideoStateInfo getVideoStateInfo() const;
	float getHeight() const;
	float getWidth() const;

private:
	ofxVlc4::MediaComponent & media() const;
	void clearPublishedFrameFenceLocked();
	void waitForPublishedFrameFenceLocked();

	ofxVlc4 & owner;
};
